=== KouassiJP1998/IDC/Rendu/Rendu 3/GPX/Rendu3-20190402T150730Z-001/Rendu3/SchemaListeLieux.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <!-- résumé : nous avons une liste de lieu, chaque lieu peut etre référencé dans differents documents et plusieurs fois dans ce meme document. 
    Un lieu est aussi composé d'un ou plusieurs points-->
  
  
  <!-- Le xml comporte une liste qui contient des lieux -->
  <xs:element name="liste">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Lieu"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- Chaque lieu est composé de point(s) et document(s)-->
  <xs:element name="Lieu">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="document"/>
        <xs:element maxOccurs="unbounded" ref="point"/>
      </xs:sequence>
      <!-- l'attribut id est relatif et unique a la liste -->
      <xs:attribute name="id" use="required" type="xs:integer"/>
      <!-- l'attribut key est une clef unique la liste qui représente le lieu sur le site internet (geoname par exemple) -->
      <xs:attribute name="key" use="required" type="xs:integer"/>
      <!-- le lien fait reference a l'endroit ou l'on trouve les informations de ce lieu -->
      <xs:attribute name="lien" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  
  <!-- un document représente le document dans lequel on retrouve ce lieu, il est composé d'élément idOrigine -->
  <xs:element name="document">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="idOrigine"/>
      </xs:sequence>
      <!-- doc origine indique le nom du document ou le lieu a été trouvé -->
      <xs:attribute name="docOrigine" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <!-- l'element id origine permet de representé l'id que porte le lieu dans un document -->
  <xs:element name="idOrigine">
    <xs:complexType>
      <xs:attribute name="idOrigine" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  
  <!-- Un point permet d'avoir la longitude, latitude, altitude ... d'un point du lieu -->
  <xs:element name="point">
    <xs:complexType>
      <xs:attribute name="altitude" type="xs:integer"/>
      <xs:attribute name="latitude" use="required" type="xs:decimal"/>
      <xs:attribute name="longitude" use="required" type="xs:decimal"/>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="place" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== KouassiJP1998/IDC/Rendu/Rendu 3/GPX/Rendu3-20190402T150730Z-001/Rendu3/listeLieux.xml
<?xml version="1.0" encoding="UTF-8"?>
<liste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./SchemaListeLieux.xsd">
    <Lieu id="0" lien="https://www.openstreetmap.org/api/0.6/node/606374063" key="606374063">
        <document docOrigine="./XMLFiles/fr_leisse.xml">
            <idOrigine idOrigine="ene.0"/>
            <idOrigine idOrigine="ene.8"/>
        </document>
        <document docOrigine="./XMLFiles/fr_pralognan.xml">
            <idOrigine idOrigine="ene.28"/>
        </document>
        <point name="Refuge de la Leisse" altitude="2487" latitude="45.3969460"
            longitude="6.8822055"/>
    </Lieu>
    <Lieu id="1" lien="https://www.openstreetmap.org/api/0.6/node/1993701388" key="1993701388">
        <document docOrigine="./XMLFiles/fr_leisse.xml">
            <idOrigine idOrigine="ene.1"/>
            <idOrigine idOrigine="ene.5"/>
        </document>
        <point name="Col de la Leisse" altitude="2761" latitude="45.4247220" longitude="6.9080562"/>
    </Lieu>
    <Lieu id="2" lien="https://www.openstreetmap.org/api/0.6/node/3294972333" key="3294972333">
        <document docOrigine="./XMLFiles/fr_leisse.xml">
            <idOrigine idOrigine="ene.3"/>
        </document>
        <point name="Plan des Nettes" place="locality" latitude="45.4030807" longitude="6.8918371"/>
    </Lieu>
    <Lieu id="3" lien="https://www.openstreetmap.org/api/0.6/way/237049410" key="237049410">
        <document docOrigine="./XMLFiles/fr_leisse.xml">
            <idOrigine idOrigine="ene.4"/>
        </document>
        <point name="Lac des Nettes" latitude="45.4112432" longitude="6.8998876"/>
        <point name="Lac des Nettes" latitude="45.4113314" longitude="6.9000533"/>
        <point name="Lac des Nettes" latitude="45.4114181" longitude="6.9002160"/>
        <point name="Lac des Nettes" latitude="45.4116486" longitude="6.8999971"/>
        <point name="Lac des Nettes" latitude="45.4119083" longitude="6.8998084"/>
        <point name="Lac des Nettes" latitude="45.4120832" longitude="6.8998876"/>
        <point name="Lac des Nettes" latitude="45.4121309" longitude="6.9000273"/>
        <point name="Lac des Nettes" latitude="45.4121653" longitude="6.9003670"/>
        <point name="Lac des Nettes" latitude="45.4122660" longitude="6.9004916"/>
        <point name="Lac des Nettes" latitude="45.4124091" longitude="6.9004954"/>
        <point name="Lac des Nettes" latitude="45.4125416" longitude="6.9004463"/>
        <point name="Lac des Nettes" latitude="45.4127642" longitude="6.9006237"/>
        <point name="Lac des Nettes" latitude="45.4130504" longitude="6.9006841"/>
        <point name="Lac des Nettes" latitude="45.4133895" longitude="6.9004991"/>
        <point name="Lac des Nettes" latitude="45.4134240" longitude="6.9003368"/>
        <point name="Lac des Nettes" latitude="45.4135618" longitude="6.9001594"/>
        <point name="Lac des Nettes" latitude="45.4136890" longitude="6.8998725"/>
        <point name="Lac des Nettes" latitude="45.4137764" longitude="6.8998310"/>
        <point name="Lac des Nettes" latitude="45.4138453" longitude="6.8999745"/>
        <point name="Lac des Nettes" latitude="45.4140387" longitude="6.9001481"/>
        <point name="Lac des Nettes" latitude="45.4142030" longitude="6.9005520"/>
        <point name="Lac des Nettes" latitude="45.4143938" longitude="6.9007483"/>
        <point name="Lac des Nettes" latitude="45.4144971" longitude="6.9010540"/>
        <point name="Lac des Nettes" latitude="45.4147091" longitude="6.9011559"/>
        <point name="Lac des Nettes" latitude="45.4148442" longitude="6.9011182"/>
        <point name="Lac des Nettes" latitude="45.4146853" longitude="6.9009030"/>
        <point name="Lac des Nettes" latitude="45.4146296" longitude="6.9006199"/>
        <point name="Lac des Nettes" latitude="45.4146694" longitude="6.9002538"/>
        <point name="Lac des Nettes" latitude="45.4145766" longitude="6.8998952"/>
        <point name="Lac des Nettes" latitude="45.4142507" longitude="6.8995706"/>
        <point name="Lac des Nettes" latitude="45.4139380" longitude="6.8996234"/>
        <point name="Lac des Nettes" latitude="45.4135008" longitude="6.8993554"/>
        <point name="Lac des Nettes" latitude="45.4135088" longitude="6.8991780"/>
        <point name="Lac des Nettes" latitude="45.4134134" longitude="6.8989402"/>
        <point name="Lac des Nettes" latitude="45.4132756" longitude="6.8989138"/>
        <point name="Lac des Nettes" latitude="45.4130477" longitude="6.8984646"/>
        <point name="Lac des Nettes" latitude="45.4128940" longitude="6.8982796"/>
        <point name="Lac des Nettes" latitude="45.4126290" longitude="6.8982268"/>
        <point name="Lac des Nettes" latitude="45.4124330" longitude="6.8983702"/>
        <point name="Lac des Nettes" latitude="45.4123429" longitude="6.8986118"/>
        <point name="Lac des Nettes" latitude="45.4123031" longitude="6.8991138"/>
        <point name="Lac des Nettes" latitude="45.4121945" longitude="6.8995970"/>
        <point name="Lac des Nettes" latitude="45.4121282" longitude="6.8997102"/>
        <point name="Lac des Nettes" latitude="45.4119825" longitude="6.8996310"/>
        <point name="Lac des Nettes" latitude="45.4118791" longitude="6.8994347"/>
        <point name="Lac des Nettes" latitude="45.4117254" longitude="6.8993781"/>
        <point name="Lac des Nettes" latitude="45.4113200" longitude="6.8993516"/>
        <point name="Lac des Nettes" latitude="45.4112299" longitude="6.8995064"/>
        <point name="Lac des Nettes" latitude="45.4112432" longitude="6.8998876"/>
    </Lieu>
    <Lieu id="4" lien="https://www.openstreetmap.org/api/0.6/node/1917284135" key="1917284135">
        <document docOrigine="./XMLFiles/fr_leisse.xml">
            <idOrigine idOrigine="ene.6"/>
        </document>
        <point name="Col de Fresse" altitude="2576" latitude="45.4402997" longitude="6.9262064"/>
    </Lieu>
    <Lieu id="5" lien="https://www.openstreetmap.org/api/0.6/node/249838326" key="249838326">
        <document docOrigine="./XMLFiles/fr_leisse.xml">
            <idOrigine idOrigine="ene.7"/>
            <idOrigine idOrigine="ene.10"/>
        </document>
        <point name="Val-Claret" place="hamlet" latitude="45.4563141" longitude="6.8999737"/>
    </Lieu>
    <Lieu id="6" lien="https://www.openstreetmap.org/api/0.6/way/97309078" key="97309078">
        <document docOrigine="./XMLFiles/fr_leisse.xml">
            <idOrigine idOrigine="ene.11"/>
        </document>
        <point name="Chalet Refuge de Lognan" altitude="2032" latitude="45.9708921"
            longitude="6.9567053"/>
        <point name="Chalet Refuge de Lognan" altitude="2032" latitude="45.9708695"
            longitude="6.9566000"/>
        <point name="Chalet Refuge de Lognan" altitude="2032" latitude="45.9707157"
            longitude="6.9566683"/>
        <point name="Chalet Refuge de Lognan" altitude="2032" latitude="45.9707250"
            longitude="6.9567113"/>
        <point name="Chalet Refuge de Lognan" altitude="2032" latitude="45.9707690"
            longitude="6.9566917"/>
        <point name="Chalet Refuge de Lognan" altitude="2032" latitude="45.9707823"
            longitude="6.9567541"/>
        <point name="Chalet Refuge de Lognan" altitude="2032" latitude="45.9708282"
            longitude="6.9567337"/>
        <point name="Chalet Refuge de Lognan" altitude="2032" latitude="45.9708921"
            longitude="6.9567053"/>
    </Lieu>
    <Lieu id="7" lien="https://www.openstreetmap.org/api/0.6/way/184939055" key="184939055">
        <document docOrigine="./XMLFiles/fr_leisse.xml">
            <idOrigine idOrigine="ene.15"/>
        </document>
        <point name="Refuge du Palet" latitude="45.4583180" longitude="6.8610850"/>
        <point name="Refuge du Palet" latitude="45.4582540" longitude="6.8610890"/>
        <point name="Refuge du Palet" latitude="45.4582590" longitude="6.8613190"/>
        <point name="Refuge du Palet" latitude="45.4583240" longitude="6.8613160"/>
        <point name="Refuge du Palet" latitude="45.4583180" longitude="6.8610850"/>
    </Lieu>
    <Lieu id="8" lien="http://api.geonames.org/get?geonameId=6442850&amp;username=unipau"
        key="6442850">
        <document docOrigine="./XMLFiles/fr_pralognan.xml">
            <idOrigine idOrigine="ene.0"/>
        </document>
        <point name="Pralognan-la-Vanoise" latitude="45.38139" longitude="6.72139"/>
    </Lieu>
    <Lieu id="9" lien="https://www.openstreetmap.org/api/0.6/way/22723011" key="22723011">
        <document docOrigine="./XMLFiles/fr_pralognan.xml">
            <idOrigine idOrigine="ene.3"/>
        </document>
        <point name="Côte du Barioz" latitude="45.3801232" longitude="6.7246029"/>
        <point name="Côte du Barioz" latitude="45.3800987" longitude="6.7242667"/>
        <point name="Côte du Barioz" latitude="45.3800591" longitude="6.7241439"/>
        <point name="Côte du Barioz" latitude="45.3799539" longitude="6.7238594"/>
        <point name="Côte du Barioz" latitude="45.3799124" longitude="6.7237211"/>
    </Lieu>
    <Lieu id="10" lien="https://www.openstreetmap.org/api/0.6/node/1785285659" key="1785285659">
        <document docOrigine="./XMLFiles/fr_pralognan.xml">
            <idOrigine idOrigine="ene.1"/>
        </document>
        <point name="La Vanoise" latitude="45.3796630" longitude="6.7233095"/>
    </Lieu>
    <Lieu id="11" lien="https://www.openstreetmap.org/api/0.6/way/33791201" key="33791201">
        <document docOrigine="./XMLFiles/fr_pralognan.xml">
            <idOrigine idOrigine="ene.2"/>
        </document>
        <point name="Petit Mont-Blanc" latitude="45.3799072" longitude="6.7230337"/>
        <point name="Petit Mont-Blanc" latitude="45.3799516" longitude="6.7232929"/>
        <point name="Petit Mont-Blanc" latitude="45.3798293" longitude="6.7233314"/>
